### ISSUE TITLE
Edit story button is bugged

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#180]
Edit button not working on My Stories page.

**Comment by gorkemkuyucu** [comment]
Previous code was requesting access to XMLHttpRequest at 'http://localhost:8081/api/story/edit/5' from origin 'http://localhost:3000' which was blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

Navigation is fixed in the handleEdit button by changing the code.
