### ISSUE TITLE
iOS and Android builds for the project

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#30]
Hello @amineglr , is it possible to create builds for the said platforms? Also, can we create a testflight and/or firebase project to upload/download the related builds? Feel free to assign other people if they can be helpful.

**Comment by amineglr** [comment]
@hdenizdogan As far as I understand, Testflight requires apple developer account which cost 99 dollars, which we don't have :). We can continue from Firebase. However, we can only get firebase-android build because again .ipa file generation requires apple developer account. We can try firebase-android build. Could you write your email that I can add to Firebase?

**Comment by amineglr** [comment]
I have send you a firebase invitation for apk build. Please let me know if everything is working fine.

**Comment by amineglr** [comment]
We can get Firebase android builds, configurations are done.
