### ISSUE TITLE
Add new features to the app bar in web app 

### ISSUE THREAD

**Issue by amineglr** [enshkn/BOUN-SWE-574-Fall-23-G2#78]
We should add recommended page and timeline page to the app bar of the web app.

**Comment by gorkemkuyucu** [comment]
![image](https://github.com/enshkn/BOUN-SWE-574-Fall-23-G2/assets/120513132/d70e19e1-6cf9-4f72-b013-747b087b3dd8)

Recommended and Timeline Search page routes are added to navbar. Recommended page is not committed because of the missing api endpoint. This subject will be followed within the issue #70 . So this issue have been closed. 

Please note that frontend won't compile since recommended component is called. Review will be asked after closing #70. development-react2 branch is created because of that.
